//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDA_0463_imd_MyProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CSV {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSV() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDA_0463_imd_MyProject.Properties.CSV", typeof(CSV).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to София;167;355;Big
        ///Пловдив;454;243;Big
        ///Варна;1095;459;Big
        ///Бургас;1005;316;Big
        ///Стара Загора;635;300;Big
        ///Русе;699;587;Big
        ///Плевен;429;500;Big
        ///Сливен;774;351;Big
        ///Пазарджик;371;253;Big
        ///Хасково;619;201;Big
        ///Шумен;897;472;Big
        ///Перник;108;335;Big
        ///Добрич;1079;530;Big
        ///Велико Търново;633;432;Big
        ///Благоевград;120;217;Big
        ///Враца;212;459;Big
        ///Ямбол;810;312;Big
        ///Асеновград;482;216;Small
        ///Габрово;571;391;Big
        ///Видин;77;616;Big
        ///Казанлък;586;339;Small
        ///Кърджали;582;142;Big
        ///Кюстендил;39;271;Big
        ///Монтана;147;498;Big [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }

        internal static string Distances
        {
            get
            {
                return ResourceManager.GetString("Distances", resourceCulture);
            }
        }
    }
}
